name: ossrh

on:
  registry_package:
    types: [published]

jobs:
  build:
    name: Sync
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 9 ]

    steps:
    - name: Import GPG key
      run: "echo $OSSRH_SIGNER_KEY | gpg --import"
      env:
        OSSRH_SIGNER_KEY: ${{ secrets.OSSRH_SIGNER_KEY }}
    - name: Checkout GitHub sources
      uses: actions/checkout@v2
    - name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: ./mvnw -B -nsu -Possrh deploy
    - name: Notify via Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        job_name: Sync
        fields: job,repo,author,took
        custom_payload: |
          {
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_JOB} of ${process.env.AS_REPO} by ${process.env.AS_AUTHOR.replace(/\<.*\>/, '')} completed in ${process.env.AS_TOOK}`,
            }]
          }
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: ${{ env.SLACK_WEBHOOK_URL != null }}
