name: ossrh

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub sources
      uses: actions/checkout@v2
    - name: Setup GitHub Packages
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Download from GitHub Packages
      run: ./mvnw -B -nsu -Pgithub.packages package dependency:copy
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Setup Maven Central
      uses: actions/setup-java@v1
      with:
        java-version: 9
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_SIGNER_KEY }}
    - name: Publish to Maven Central
      run: ./mvnw -B -nsu -Possrh deploy
    - name: Notify via Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: job,repo,author,took
        custom_payload: |
          {
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_JOB} of ${process.env.AS_REPO} by ${process.env.AS_AUTHOR.replace(/\<.*\>/, '')} completed in ${process.env.AS_TOOK}`,
            }]
          }
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      if: ${{ env.SLACK_WEBHOOK_URL != null }}
